# Site Settings
name: iStandpoint
title: iStandpoint | The Blog of Sarthak Garg
description: "Informal notes on product management and artificial intelligence. Short stories, that's icing on the cake!"
tags:
  - blog
  - fiction
  - product
  - ai
  - tech
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Categories
    url: /category
  - title: Contact
    url: /contact
email: gargsaar@gmail.com
# See: https://disqus.com/
disqus_username: sg-istandpoint
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: gargsaar
twitter_username: gargsaar
linkedin_username: sarthak-garg-0997a418


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://sarthakgarg.com" # the base hostname & protocol for your site
google_analytics: "" #hardcoded in stats.html
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
theme: jekflix
version: v3.1.2
